/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.anime.downloader.maven.graphics;

import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;



/**
 *
 * @author cr998
 */
public class Displya extends javax.swing.JFrame {

    
    /**
     * Creates new form Displya
     */
    public Displya() throws MalformedURLException, IOException {
        initComponents();
        String path = "http://www.animeyt.tv/files/img/series/s_3167_poster.jpeg";
//        URL url = new URL(path);
//        HttpURLConnection connection = (HttpURLConnection) url
//        .openConnection();
//connection.setRequestProperty(
//    "User-Agent",
//    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.65 Safari/537.31");
//
//        BufferedImage image = ImageIO.read(connection.getInputStream());
//        ImageIcon imageic = new ImageIcon(image);
//        JLabel label = new JLabel(imageic);
//        label.setSize(imageic.getIconWidth(), imageic.getIconHeight());
//        this.zonaBusqueda.add(label);
        this.Descargas.setLayout(new GridLayout(3,2));
        this.Descargas.add(new Imagen(path));
        this.Descargas.add(new Imagen(path));
        this.Descargas.add(new Imagen(path));
        this.Descargas.add(new Imagen(path));
        this.Descargas.add(new Imagen(path));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Buscador = new javax.swing.JPanel();
        areatextoBuscador = new javax.swing.JTextField();
        botonBuscador = new javax.swing.JButton();
        zonaBusqueda = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Descargas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anime Downloader");

        areatextoBuscador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        areatextoBuscador.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        areatextoBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areatextoBuscadorActionPerformed(evt);
            }
        });

        botonBuscador.setText("Buscar");
        botonBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zonaBusquedaLayout = new javax.swing.GroupLayout(zonaBusqueda);
        zonaBusqueda.setLayout(zonaBusquedaLayout);
        zonaBusquedaLayout.setHorizontalGroup(
            zonaBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        zonaBusquedaLayout.setVerticalGroup(
            zonaBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BuscadorLayout = new javax.swing.GroupLayout(Buscador);
        Buscador.setLayout(BuscadorLayout);
        BuscadorLayout.setHorizontalGroup(
            BuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuscadorLayout.createSequentialGroup()
                        .addGap(0, 352, Short.MAX_VALUE)
                        .addComponent(areatextoBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscador))
                    .addComponent(zonaBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        BuscadorLayout.setVerticalGroup(
            BuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areatextoBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(zonaBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscador", Buscador);

        javax.swing.GroupLayout DescargasLayout = new javax.swing.GroupLayout(Descargas);
        Descargas.setLayout(DescargasLayout);
        DescargasLayout.setHorizontalGroup(
            DescargasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DescargasLayout.setVerticalGroup(
            DescargasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Descargas", Descargas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Anime");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areatextoBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areatextoBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areatextoBuscadorActionPerformed

    private void botonBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buscador;
    private javax.swing.JPanel Descargas;
    private javax.swing.JTextField areatextoBuscador;
    private javax.swing.JButton botonBuscador;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel zonaBusqueda;
    // End of variables declaration//GEN-END:variables
}
